FROM mcr.microsoft.com/devcontainers/python:3.10
#WORKDIR /code
# install dependencies
#COPY ./requirements.txt ./
#RUN pip install --no-cache-dir --upgrade -r requirements.txt

# start the server
#CMD ["tail", "-f", "/dev/null"]